#!/usr/bin/env bash

DRY_RUN=false

while getopts "d" opt; do
    case "$opt" in
        d) DRY_RUN=true ;;
    esac
done

changed_files=$(git diff --staged --name-only --diff-filter=ACMR)
changed_frontend_files=$(echo "$changed_files" | grep "frontend/.*")
changed_backend_files=$(echo "$changed_files" | grep "backend/.*")

if [[ ! -z $changed_frontend_files ]]; then
    if [ $DRY_RUN = true ]; then
        echo "The following frontend files were found to have changed"
        echo $changed_frontend_files
    else
        cd frontend
        npm run lint:fix
        echo "$changed_frontend_files" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
        cd ..
        git add $changed_frontend_files
    fi
fi

if [[ ! -z $changed_backend_files ]]; then
    if [ $DRY_RUN = true ]; then
        echo "The following backend files were found to have changed"
        echo $changed_backend_files
    else
        if ! command -v golangci-lint &> /dev/null; then
            echo "Could not find the golangci-lint command. Please install locally per instructions here: https://golangci-lint.run/welcome/install/#local-installation"
            exit 1
        fi

        cd backend
        golangci-lint run --fix
        go fmt ./...
        cd ..
        git add $changed_backend_files
    fi
fi
