#!/usr/bin/env bash

DRY_RUN=false

while getopts "d" opt; do
    case "$opt" in
        d) DRY_RUN=true ;;
    esac
done

changed_files=$(git diff --staged --name-only --diff-filter=ACMR)
changed_frontend_files=$(echo "$changed_files" | grep "frontend/.*")
changed_backend_files=$(echo "$changed_files" | grep "backend/.*")

if [[ ! -z $changed_frontend_files ]]; then
    if [ $DRY_RUN = true ]; then
        echo "The following files were found to have changed and would have triggered a formatting error"
        echo $changed_frontend_files
    else
        cd frontend
        npm run lint:fix
        cd ..
        git add $changed_frontend_files
    fi
fi

if [[ ! -z $changed_backend_files ]]; then
    if [ $DRY_RUN = true ]; then
        echo "The following files were found to have changed and would have triggered a formatting error"
        echo $changed_backend_files
    else
        cd backend
        go fmt ./...
        cd ..
        git add $changed_backend_files
    fi
fi
