services:
  client:
    build:
      context: client
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      context: backend
      target: dev
    volumes:
      - ./backend:/app
      - /app/tmp
