services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    depends_on:
      - backend
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  client:
    build:
      context: client
      target: ${CLIENT_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: backend
    ports:
      - "8080:8080"
