# Workflow to ensure that all backend tests pass
name: Backend test

on: pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v
