# Workflow to enforce best practices
name: Frontend lint

on: pull_request

jobs:
  linting:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Install dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
